import { C } from "./constants.js";

// Unica fonte per i 3 tipi di distribuzione (Step1 e Preventivo Rapido).
// Estratta da Step1 senza cambiare nessun valore.
export const distributionTypes = [
  {
    id: "d2d",
    name: "Door to Door",
    code: "D2D",
    icon: "mailbox",
    badge: "Più richiesto",
    desc: "Distribuzione capillare in cassette postali, condomini, palazzi, villette e zone residenziali.",
    explanation: "Consegniamo volantini e materiale promozionale direttamente nelle cassette postali di famiglie e residenti.",
    howItWorks: "Distribuzione capillare direttamente nelle cassette postali di famiglie e residenti dell'area selezionata.",
    useCases: "Attività locali, nuove aperture, promozioni stagionali e volantini offerte.",
    benefits: "Copertura sistematica di tutte le famiglie della zona per un impatto visivo duraturo.",
    target: "Famiglie e residenti di quartiere",
    coverage: "Alta densità residenziale",
    time: "5–7 giorni lavorativi",
    color: C.orange,
  },
  {
    id: "h2h",
    name: "Hand to Hand",
    code: "H2H",
    icon: "handshake",
    badge: "Alta Conversione",
    desc: "Distribuzione manuale e diretta da parte di promoter qualificati in punti ad alto flusso pedonale.",
    explanation: "Promoter dedicati consegnano a mano il materiale promozionale a persone e passanti in punti strategici.",
    howItWorks: "Promoter dedicati presidiano i punti e le fasce orarie a maggior flusso pedonale per il massimo contatto.",
    useCases: "Eventi, inaugurazioni di negozi, palestre, promozioni immediate e flash.",
    benefits: "Contatto umano immediato e selezione visiva del target ideale.",
    target: "Persone, passanti, studenti, pendolari e shopper",
    coverage: "Piazze, stazioni e vie nevralgiche",
    time: "Giornata / Fascia oraria mirata",
    color: C.teal,
  },
  {
    id: "b2b",
    name: "Distribuzione Business",
    code: "B2B",
    icon: "building",
    badge: "Mirato B2B",
    desc: "Distribuzione mirata presso aziende, negozi, uffici e professionisti selezionati in base al tuo target.",
    explanation: "Consegniamo volantini, brochure, cataloghi e materiale promozionale direttamente presso attività e sedi professionali selezionate.",
    howItWorks: "Selezioniamo le attività più adatte al tuo target e consegniamo direttamente presso le sedi.",
    useCases: "Forniture B2B, presentazione servizi, cataloghi professionali, offerte dedicate alle aziende, convenzioni, Ho.Re.Ca. e attività commerciali.",
    benefits: "Consegna qualificata a reception o direttamente ai responsabili decisionali.",
    target: "Imprenditori, titolari di attività, professionisti, responsabili acquisti, uffici e commercianti.",
    coverage: "Aree commerciali e centri direzionali",
    time: "3–5 giorni lavorativi",
    color: C.green,
  },
];
