import test from 'node:test';
import assert from 'node:assert/strict';
import { initialInputs, cell, normalizeField, parseNumber, validationErrors, nextMissing, scenariosFromHistory } from '../src/pages/customer/feasibility/feasibilitySchemas.js';
import { calculateFeasibility } from '../src/pages/customer/feasibility/feasibilityEngine.js';
import { applyEvidence } from '../src/pages/customer/feasibility/feasibilityAi.js';
import { NARRATIVE_OPTIONS, validateNarrative } from '../src/pages/customer/feasibility/feasibilityPrompt.js';
import { readFeasibility, saveFeasibility, STORAGE_KEY } from '../src/pages/customer/feasibility/feasibilityStorage.js';
import { createHandler } from '../supabase/functions/feasibility-ai/handler.js';
function fixture(cost = 420, qty = 10000) { return { ...initialInputs({ total: cost, quantity: qty, municipalities: ['Milano'], areas: ['Milano'], service: 'd2d' }), businessType: cell('Palestra', 'user_provided'), averageCustomerRevenue: cell(400, 'user_provided'), averageCustomerMargin: cell(180, 'user_provided'), targetNewCustomers: cell(10, 'user_provided') }; }
const approx = (actual, expected) => assert.ok(Math.abs(actual - expected) < 1e-9, `${actual} != ${expected}`);
test('cent arithmetic avoids an extra customer at decimal break-even', () => { const i = fixture(.07); i.averageCustomerMargin = cell(.01, 'user_provided'); const r = calculateFeasibility(i); assert.equal(r.breakEvenCustomers, 7); assert.equal(r.target.netResult, .03); i.averageCustomerMargin.value = .015; assert.throws(() => calculateFeasibility(i), /INVALID_INPUT/); });
test('required example: cost 1200, margin 180, 20000 flyers, 10 customers', () => {
 const input = fixture(1200, 20000), before = structuredClone(input), r = calculateFeasibility(input);
 assert.equal(r.breakEvenCustomers, 7); approx(r.breakEvenConversion, .00035); assert.equal(r.target.contribution, 1800); assert.equal(r.target.netResult, 600); assert.equal(r.target.roi, 50); assert.equal(r.target.cac, 120); assert.deepEqual(input, before);
});
test('Milano runtime fixture exact financial values', () => { const r = calculateFeasibility(fixture()); assert.equal(r.breakEvenCustomers, 3); approx(r.breakEvenConversion, .0003); approx(r.targetConversion, .001); assert.equal(r.target.contribution, 1800); assert.equal(r.target.netResult, 1380); approx(r.target.roi, 328.57142857142856); assert.equal(r.target.cac, 42); assert.equal(r.target.revenueGenerated, 4000); assert.equal(r.classification, 'GO'); });
test('zero cost, zero customers and zero margin have finite explicit semantics', () => {
 const i = fixture(0); i.targetNewCustomers = cell(0, 'user_provided'); let r = calculateFeasibility(i); assert.equal(r.breakEvenCustomers, 0); assert.equal(r.target.roi, null); assert.equal(r.target.cac, null); assert.equal(r.classification, 'GO');
 i.averageCustomerMargin = cell(0, 'user_provided'); i.campaignCost = cell(420, 'user_provided'); r = calculateFeasibility(i); assert.equal(r.breakEvenCustomers, null); assert.equal(r.breakEvenConversion, null); assert.equal(r.classification, 'HIGH RISK'); assert.equal(r.target.roi, -100);
 i.campaignCost = cell(0, 'user_provided'); assert.equal(calculateFeasibility(i).classification, 'HIGH RISK');
});
test('decimal inputs, expected customers and practical whole interpretation', () => { const i = fixture(420.25, 15000); i.averageCustomerMargin = cell(180.5, 'user_provided'); const r = calculateFeasibility(i); assert.equal(r.scenarios[1].expectedCustomers, 7.5); assert.deepEqual(r.scenarios[1].practicalRange, [7, 8]); assert.equal(r.scenarios[1].contribution, 1353.75); assert.equal(r.scenarios[1].netResult, 933.5); });
test('classification thresholds explicit on both boundaries', () => { const i = fixture(1000); i.averageCustomerMargin = cell(100, 'user_provided'); i.scenarioConversionConservative = cell(.0005, 'model_assumption'); i.scenarioConversionRealistic = cell(.001, 'model_assumption'); assert.equal(calculateFeasibility(i).classification, 'GO'); i.scenarioConversionConservative.value = .000499; assert.equal(calculateFeasibility(i).classification, 'GO WITH CONDITIONS'); i.scenarioConversionRealistic.value = .0008; assert.equal(calculateFeasibility(i).classification, 'GO WITH CONDITIONS'); i.scenarioConversionRealistic.value = .000799; assert.equal(calculateFeasibility(i).classification, 'HIGH RISK'); });
test('invalid values cannot enter calculations', () => {
 for (const [key, value] of [['campaignCost', -1], ['campaignCost', NaN], ['averageCustomerRevenue', Infinity], ['flyerQuantity', 0], ['flyerQuantity', 1.5], ['scenarioConversionRealistic', 1.01], ['targetNewCustomers', -1], ['targetNewCustomers', 2.5], ['campaignCost', 1e10]]) { const i = fixture(); i[key] = cell(value, 'user_provided'); assert.throws(() => calculateFeasibility(i), /INVALID_INPUT/); }
 const i = fixture(); i.marketingBudget = normalizeField('marketingBudget', 'abc'); assert.ok(validationErrors(i).marketingBudget); assert.throws(() => calculateFeasibility(i));
 i.marketingBudget = cell(); i.averageCustomerMargin = cell(500, 'user_provided'); assert.throws(() => calculateFeasibility(i)); assert.equal(calculateFeasibility(i, { unusualMargin: true }).firstPurchaseCACCeiling, 500);
});
test('large safe values and overflow/subnormal inputs', () => { const i = fixture(1e9, 1e9); i.averageCustomerRevenue = cell(1e6, 'user_provided'); i.averageCustomerMargin = cell(1e5, 'user_provided'); assert.ok(Number.isFinite(calculateFeasibility(i).target.roi)); i.averageCustomerMargin.value = Number.MIN_VALUE; assert.throws(() => calculateFeasibility(i), /INVALID_INPUT/); });
test('Italian numeric normalization, ambiguity rejected, provenance retained', () => { for (const [raw, value] of [['circa 200 euro', 200], ['1.200,50 euro', 1200.5], ['10.000', 10000], ['0,05%', .05], ['180.5', 180.5]]) assert.equal(parseNumber(raw), value); for (const raw of ['400 oppure 500', '1e309', 'NaN', 'Infinity', '20 mila']) assert.equal(parseNumber(raw), null); assert.deepEqual(normalizeField('averageCustomerMargin', 'circa 200 euro'), cell(200, 'user_provided')); assert.deepEqual(normalizeField('knownConversionRate', '0,05%'), cell(.0005, 'user_provided')); });
test('known conversion produces explicit scaled/capped assumptions', () => { const i = fixture(); i.knownConversionRate = cell(.0005, 'user_provided'); let next = scenariosFromHistory(i); approx(next.scenarioConversionConservative.value, .0003); assert.equal(next.scenarioConversionGrowth.value, .001); assert.equal(next.scenarioConversionRealistic.source, 'model_assumption'); i.knownConversionRate.value = .8; assert.equal(scenariosFromHistory(i).scenarioConversionGrowth.value, 1); });
test('AI evidence cannot override campaign or add invented/unrelated fields', () => { const i = fixture(), before = structuredClone(i); const next = applyEvidence(i, [{ field: 'campaignCost', evidence: '999' }, { field: 'averageCustomerMargin', evidence: '999' }, { field: 'targetNewCustomers', evidence: '27' }, { field: 'payment_status', evidence: '999' }, { field: '__proto__', evidence: '999' }], '999'); assert.equal(next.campaignCost.value, 420); assert.equal(next.averageCustomerMargin.value, 999); assert.equal(next.targetNewCustomers.value, 10); assert.equal(next.payment_status, undefined); assert.deepEqual(i, before); assert.ok(validationErrors(next).averageCustomerMargin); });
test('missing question skips preloaded campaign and records one natural answer', () => { const i = initialInputs({ total: 420, quantity: 10000, municipalities: ['Milano'] }); assert.equal(nextMissing(i), 'businessType'); const next = applyEvidence(i, [{ field: 'businessType', evidence: 'palestra' }], 'Ho una palestra.'); assert.equal(nextMissing(next), 'averageCustomerRevenue'); assert.equal(next.campaignCost.value, 420); });
test('narrative rejects invented text/numbers and only returns curated qualitative interpretation', () => { const sections = Object.fromEntries(Object.entries(NARRATIVE_OPTIONS).map(([key, options]) => [key, Object.keys(options)[0]])); assert.ok(validateNarrative({ sections })); assert.equal(validateNarrative({ sections: { ...sections, executive: 'ROI 999% garantito' } }), null); assert.equal(validateNarrative({ sections: { ...sections, classification: 'GO' } }), null); assert.equal(validateNarrative({ sections: {} }), null); const i = fixture(), before = calculateFeasibility(i); validateNarrative({ sections, roi: 9999, classification: 'HIGH RISK' }); assert.deepEqual(calculateFeasibility(i), before); });
test('local session saves normalized fields only; quote/payment untouched; different campaign resets', () => { const map = new Map(), quote = { payment_status: 'pending', total: 420 }; const browser = { history: { state: { feasibility: { total: 420, quantity: 10000, municipalities: ['Milano'] } } }, sessionStorage: { getItem: k => map.get(k), setItem: (k,v) => map.set(k,v) }, localStorage: { getItem: () => quote, setItem: () => assert.fail('campaign write') } }; const state = readFeasibility(browser); state.inputs.businessType = cell('Palestra', 'user_provided'); state.phase = 3; state.messages = ['private chat']; assert.equal(saveFeasibility(browser, state), true); assert.doesNotMatch(map.get(STORAGE_KEY), /private chat|payment_status/); assert.equal(readFeasibility(browser).phase, 1); assert.equal(readFeasibility(browser).inputs.businessType.value, 'Palestra'); browser.history.state.feasibility.total = 500; assert.equal(readFeasibility(browser).inputs.businessType.value, null); assert.equal(quote.total, 420); });
const req = (body, headers = {}) => new Request('https://example.test', { method: 'POST', headers: { origin: 'https://volantinipro-clean.vercel.app', apikey: 'anon', authorization: 'Bearer anon', ...headers }, body: JSON.stringify(body) });
test('edge rejects origin/auth/invalid request and does not call AI', async () => { let calls = 0; const handler = createHandler({ apiKey: 'server-secret', anonKey: 'anon', fetcher: async () => { calls++; throw new Error(); } }); assert.equal((await handler(req({}, { origin: 'https://evil.test' }))).status, 403); assert.equal((await handler(req({}, { apikey: 'wrong' }))).status, 401); assert.equal((await handler(req({ mode: 'narrative', inputs: initialInputs() }))).status, 400); assert.equal(calls, 0); });
test('edge AI failure returns safe fallback response without secrets', async () => { const handler = createHandler({ apiKey: 'server-secret', anonKey: 'anon', fetcher: async () => { throw new Error('secret'); } }); const response = await handler(req({ mode: 'narrative', inputs: fixture() })); assert.equal(response.status, 503); assert.doesNotMatch(await response.text(), /server-secret/); });
test('edge recomputes canonical financial outputs and filters model response', async () => { let sent; const sections = Object.fromEntries(Object.entries(NARRATIVE_OPTIONS).map(([key, options]) => [key, Object.keys(options)[0]])); const handler = createHandler({ apiKey: 'secret', anonKey: 'anon', fetcher: async (url, options) => { sent = JSON.parse(options.body); return Response.json({ choices: [{ message: { content: JSON.stringify({ sections, roi: 999 }) } }] }); } }); const response = await handler(req({ mode: 'narrative', inputs: fixture(), calculations: { roi: 999 } })); assert.equal(response.status, 200); const payload = JSON.parse(sent.messages[1].content); assert.equal(payload.calculations.target.cac, 42); assert.match(sent.messages[0].content, /Do not recalculate or invent numerical values/); assert.deepEqual(await response.json(), { sections }); });
test('edge per-isolate request budget bounds AI calls', async () => { let calls = 0; const handler = createHandler({ apiKey: 'secret', anonKey: 'anon', now: () => 100, fetcher: async () => { calls++; return Response.json({ choices: [{ message: { content: '{"updates":[]}' } }] }); } }); for (let i = 0; i < 15; i++) assert.equal((await handler(req({ mode: 'collect', inputs: fixture(), message: 'palestra', currentField: 'businessType' }))).status, 200); assert.equal((await handler(req({ mode: 'collect', inputs: fixture(), message: 'palestra' }))).status, 429); assert.equal(calls, 15); });
