// Studio Mappa — la copertura AUTOMATICA finisce in project.features, col
// colore dell'operatore, ed è renderizzata in un pane dedicato sopra base/
// boundary. Rigenerare sostituisce SOLO l'automatico di quell'operatore.
import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import React from 'react';
import TestRenderer, { act } from 'react-test-renderer';

globalThis.IS_REACT_ACT_ENVIRONMENT = true;
globalThis.React = React;
function mem() { const s = new Map(); return { getItem: (k) => (s.has(k) ? s.get(k) : null), setItem: (k, v) => s.set(k, String(v)), removeItem: (k) => s.delete(k), clear: () => s.clear() }; }
globalThis.window = { localStorage: mem(), setTimeout: () => 0, clearTimeout: () => {}, addEventListener: () => {}, removeEventListener: () => {} };

const read = (p) => readFileSync(new URL(`../${p}`, import.meta.url), 'utf8');
const CANVAS = read('src/pages/admin/map-studio/MapStudioCanvas.jsx');
const AUTO = read('src/pages/admin/map-studio/AutoCoveragePanel.jsx');
const PAGE = read('src/pages/admin/map-studio/MapStudioPage.jsx');

const { useMapStudioProject } = await import('../src/pages/admin/map-studio/useMapStudioProject.js');
const { createProject, createOperator } = await import('../src/pages/admin/map-studio/mapStudioProject.js');
const { loadProject } = await import('../src/pages/admin/map-studio/mapStudioStorage.js');

// ── contratto sorgente: pane / z-order / casing ──────────────────────
test('MapStudioCanvas: 5 pane dedicati con z-order boundary < network < auto < manual < points', () => {
  for (const p of ['ms-boundary', 'ms-network', 'ms-auto', 'ms-manual', 'ms-points']) {
    assert.match(CANVAS, new RegExp(`<Pane name="${p}"`), `manca <Pane name="${p}">`);
  }
  const z = CANVAS.match(/PANE_Z = \{[^}]*\}/)[0];
  const val = (k) => Number(new RegExp(`${k}:\\s*(\\d+)`).exec(z)[1]);
  assert.ok(val('boundary') < val('network'));
  assert.ok(val('network') < val('auto'));
  assert.ok(val('auto') < val('manual'));
  assert.ok(val('manual') < val('points'));
});

test('MapStudioCanvas: auto lines = casing bianco + core colore operatore, nel pane ms-auto, gate su layers.auto.visible', () => {
  const seg = CANVAS.slice(CANVAS.indexOf('COPERTURA AUTOMATICA'), CANVAS.indexOf('COPERTURA MANUALE'));
  assert.match(seg, /layers\.auto\.visible && autoLines\.map/);
  assert.match(seg, /color: '#ffffff', weight: core \+ 3/); // casing
  assert.match(seg, /pane="ms-auto"/);
  assert.match(seg, /renderer: R\.auto/);
  // colore = swatch VIVO operatore
  assert.match(CANVAS, /const color = op\?\.color \|\| f\.style\?\.color/);
});

test('MapStudioCanvas: toggle layer Automatico nasconde davvero le linee auto', () => {
  // niente rendering di autoLines fuori dalla guardia layers.auto.visible
  assert.doesNotMatch(CANVAS, /autoLines\.map\([^)]*\)[\s\S]{0,40}Polyline(?![\s\S]{0,400}layers\.auto\.visible)/);
  assert.match(CANVAS, /\{layers\.auto\.visible && autoLines\.map/);
});

test('MapStudioCanvas + Page: fit sulla copertura appena generata (fitAutoTick)', () => {
  assert.match(CANVAS, /fitAutoTick/);
  assert.match(CANVAS, /map\.fitBounds\(autoPoints, \{ padding: \[40, 40\], maxZoom: 16 \}\)/);
  assert.match(PAGE, /const \[fitAutoTick, setFitAutoTick\] = useState\(0\)/);
  assert.match(PAGE, /onAutoGenerated=\{\(\) => setFitAutoTick\(\(t\) => t \+ 1\)\}/);
  assert.match(PAGE, /fitAutoTick=\{fitAutoTick\}/);
});

// ── contratto sorgente: AutoCoveragePanel ───────────────────────────
test('AutoCoveragePanel: operatore automatico segue drawing.activeOperatorId; stampa style.color; rigenera per-operatore', () => {
  assert.match(AUTO, /const chosenOperatorId = auto\.operatorId \|\| drawing\.activeOperatorId \|\| project\.operators\[0\]\?\.id/);
  assert.match(AUTO, /const opId = chosenOperatorId;/);
  assert.match(AUTO, /style: opColor \? \{ color: opColor \} : null/);
  // clear SOLO l'automatico di questo operatore (non tutto l'automatico)
  assert.match(AUTO, /ops\.clearFeatures\(\(f\) => f\.source === 'auto' && f\.operatorId === opId\)/);
  assert.doesNotMatch(AUTO, /ops\.clearFeatures\(\(f\) => f\.source === 'auto'\)\s*;/);
  assert.match(AUTO, /onAutoGenerated\(\)/);
  // select riflette l'operatore effettivo
  assert.match(AUTO, /value=\{chosenOperatorId \|\| ''\}/);
});

// ── comportamento: due operatori con automatico coesistono ──────────
function Harness({ apiRef, seed }) { apiRef.current = useMapStudioProject(seed); return null; }
function mount(seed) { const r = { current: null }; act(() => { TestRenderer.create(React.createElement(Harness, { apiRef: r, seed })); }); return r; }

const line = (a, b) => [[45.6 + a * 0.001, 9.14], [45.6 + a * 0.001, 9.15], [45.6 + b * 0.001, 9.16]];

test('T7 — genera op4 poi op1: entrambe le coperture automatiche coesistono, colori distinti', () => {
  const [op1, op2, op3, op4] = [0, 1, 2, 3].map((i) => createOperator({ index: i, name: `Operatore ${i + 1}` }));
  const seed = createProject({ name: 'Seveso', municipality: 'Seveso', operators: [op1, op2, op3, op4] });
  const api = mount(seed);

  // "genera" op4 (simula ciò che fa handleGenerate)
  act(() => {
    api.current.ops.clearFeatures((f) => f.source === 'auto' && f.operatorId === op4.id);
    api.current.ops.addFeatures([0, 1, 2].map((k) => ({ operatorId: op4.id, type: 'line', source: 'auto', style: { color: op4.color }, geometry: line(k, k + 1) })), 'auto');
  });
  assert.equal(api.current.project.features.filter((f) => f.source === 'auto').length, 3);

  // "genera" op1
  act(() => {
    api.current.ops.clearFeatures((f) => f.source === 'auto' && f.operatorId === op1.id);
    api.current.ops.addFeatures([0, 1].map((k) => ({ operatorId: op1.id, type: 'line', source: 'auto', style: { color: op1.color }, geometry: line(k + 5, k + 6) })), 'auto');
  });
  const auto = api.current.project.features.filter((f) => f.source === 'auto');
  assert.equal(auto.length, 5, 'op4 (3) + op1 (2) coesistono');
  assert.equal(auto.filter((f) => f.operatorId === op4.id).length, 3);
  assert.equal(auto.filter((f) => f.operatorId === op1.id).length, 2);
  assert.notEqual(op1.color, op4.color);
  assert.equal(auto.find((f) => f.operatorId === op4.id).style.color, op4.color);

  // RIGENERA op4 → sostituisce SOLO op4, op1 intatto, nessun duplicato
  act(() => {
    api.current.ops.clearFeatures((f) => f.source === 'auto' && f.operatorId === op4.id);
    api.current.ops.addFeatures([0, 1, 2, 3].map((k) => ({ operatorId: op4.id, type: 'line', source: 'auto', style: { color: op4.color }, geometry: line(k, k + 1) })), 'auto');
  });
  const auto2 = api.current.project.features.filter((f) => f.source === 'auto');
  assert.equal(auto2.filter((f) => f.operatorId === op4.id).length, 4, 'op4 rigenerato (4), non 3+4');
  assert.equal(auto2.filter((f) => f.operatorId === op1.id).length, 2, 'op1 intatto');
});

test('save/reload: le linee automatiche restano (source=auto, operatorId, style.color)', () => {
  const op = createOperator({ index: 0, name: 'A' });
  const seed = createProject({ name: 'Persist auto', municipality: 'Seveso', operators: [op] });
  const api = mount(seed);
  act(() => {
    api.current.ops.addFeatures([0, 1, 2].map((k) => ({ operatorId: op.id, type: 'line', source: 'auto', style: { color: op.color }, geometry: line(k, k + 1) })), 'auto');
  });
  let id;
  act(() => { id = api.current.persistence.save().project.id; });
  const back = loadProject(id);
  const auto = back.features.filter((f) => f.source === 'auto');
  assert.equal(auto.length, 3);
  assert.ok(auto.every((f) => f.operatorId === op.id));
  assert.ok(auto.every((f) => f.style && f.style.color === op.color));
});
