export function resolveAppRoute(path, { hasAuthHash = false, prefillHas = false, step = null } = {}) {
  const p = String(path || '/').toLowerCase();
  if (hasAuthHash) return 'login';
  if (p === '/auth/callback') return 'login';
  if (p === '/admin' || p === '/admin/dashboard') return 'admin';
  if (p === '/admin/live') return 'admin-live';
  if (p === '/admin/operations') return 'admin-operations';
  if (p === '/admin/operations/report' || p === '/admin/daily-report') return 'admin-daily-report';
  if (p === '/admin/clients-quotes') return 'admin-clients-quotes';
  if (p === '/admin/orders') return 'admin-orders';
  if (p === '/admin/groups') return 'admin-groups-manager';
  if (p === '/admin/commercial') return 'admin-commercial';
  if (p === '/admin/smart-pairing') return 'admin-smart-pairing';
  if (p === '/admin/suppliers') return 'admin-suppliers';
  if (p === '/admin/status') return 'admin-status';
  if (p === '/admin/map-studio') return 'admin-map-studio';
  if (p === '/admin/analytics') return 'admin-analytics';
  if (p === '/admin/communications') return 'admin-communications';
  const adminAssignmentsNew = p.match(/^\/admin\/campaigns\/([^/]+)\/assignments\/new$/);
  if (adminAssignmentsNew) return `admin-assignments-new:${adminAssignmentsNew[1]}`;
  const adminCoverageEditor = p.match(/^\/admin\/campaigns\/([^/]+)\/coverage-editor$/);
  if (adminCoverageEditor) return `admin-coverage-editor:${adminCoverageEditor[1]}`;
  const adminRoute = p.match(/^\/admin\/campaigns\/([^/]+)\/(gps|operations|groups|report|assignments)$/);
  if (adminRoute) return `admin-${adminRoute[2]}:${adminRoute[1]}`;
  if (p.startsWith('/admin')) return 'admin';
  const customerRoute = p.match(/^\/(?:customer\/campaigns|cliente\/campagna|campagna|dashboard)\/([^/]+)\/(tracking|report|pagamento|payment)$/);
  if (customerRoute) {
    const action = customerRoute[2] === 'pagamento' ? 'payment' : customerRoute[2];
    return `customer-${action}:${customerRoute[1]}`;
  }
  const dashboardCampaign = p.match(/^\/(?:dashboard|campagna|cliente\/campagna)\/([^/]+)$/);
  if (dashboardCampaign) return `campaign:${dashboardCampaign[1]}`;
  if (p === '/cliente/dashboard') return 'dashboard';
  if (p.startsWith('/customer/') || p.startsWith('/dashboard/') || p.startsWith('/campagna/') || p.startsWith('/cliente/')) return 'not-found';
  if (p === '/supplier' || p === '/supplier/dashboard') return 'supplier-dashboard';
  if (p === '/' || p === '/index.html' || p === '/volantinipro-final.jsx') return 'home';
  if (p === '/login') return 'login';
  if (p === '/dashboard') return 'dashboard';
  if (p === '/privacy') return 'privacy';
  if (p === '/termini' || p === '/terms') return 'terms';
  if (p === '/cookie-policy' || p === '/cookie') return 'cookie';
  if (p === '/preventivo') return 'preventivo';
  if (p === '/preventivo-rapido') return 'quick';
  if (p === '/consulente') return 'consultant';
  if (p === '/servizi/door-to-door') return 'service-door-to-door';
  if (p === '/servizi/hand-to-hand') return 'service-hand-to-hand';
  if (p === '/servizi/business') return 'service-business';
  if (p === '/distribuzione-volantini-milano') return 'milano-landing';
  if (p === '/configuratore' || prefillHas) return step ? `step${step}` : 'step1';
  return 'not-found';
}
