import puppeteer from 'puppeteer-core';
import assert from 'node:assert/strict';
import {writeFileSync,readFileSync} from 'node:fs';
const out='qa-step2-map-restoration',results=process.env.START_AT ? JSON.parse(readFileSync(`${out}/production.json`,'utf8')).filter(r=>process.env.START_AT==='iphone' ? r.viewport!=='iphone' : r.viewport==='desktop') : [],delay=ms=>new Promise(r=>setTimeout(r,ms));
const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--no-sandbox']});
try{for(const [label,width,height] of [['desktop',1440,900],['samsung',412,915],['iphone',390,844]]){
 if(process.env.START_AT==='samsung'&&label==='desktop'||process.env.START_AT==='iphone'&&label!=='iphone')continue;
 const ctx=await browser.createBrowserContext(),p=await ctx.newPage();await p.setViewport({width,height});const errors=[],network=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('response',async r=>{if(r.status()>=400)network.push({url:r.url().split('?')[0],status:r.status()});});p.on('requestfailed',r=>network.push({url:r.url().split('?')[0],error:r.failure()?.errorText}));
 await p.goto(`${process.env.BASE_URL||'https://www.volantinipro.it'}/configuratore?step=2&service=d2d&qty=10000`,{waitUntil:'networkidle2',timeout:90000});
 // Read the real Leaflet instance from its existing React ref. No app state or data changes.
 await p.evaluate(()=>{window.__qaMap=()=>{const el=document.querySelector('.leaflet-container');if(!el)return null;let f=el[Object.keys(el).find(k=>k.startsWith('__reactFiber$'))];for(;f;f=f.return){let h=f.memoizedState;for(let i=0;h&&i<100;i++,h=h.next){const v=h.memoizedState?.current;if(v?.eachLayer&&v?.latLngToContainerPoint)return v;}}return null;};});
 async function state(){return p.evaluate(()=>{const m=window.__qaMap(),polygons=[],points=[];let boundary=0;m?.eachLayer(l=>{if(l.options?.vpZoneId!==undefined)polygons.push({id:l.options.vpZoneId,name:l.options.vpZoneName,type:l.options.vpZoneType,fill:l.options.fillOpacity,weight:l.options.weight});if(l.getLatLng)points.push({point:l.getLatLng(),radius:l.getRadius?.()});if(l.options?.pane==='municipalityBoundaryPane'&&l.getBounds)boundary++;});return {polygons,points,boundary,summary:document.querySelector('.vp-milano-summary')?.innerText,overflow:document.documentElement.scrollWidth>innerWidth,rows:[...document.querySelectorAll('.vp-milano-radius-context > ul > li')].map(e=>e.innerText)};});}
 async function snap(name){await delay(700);const s=await state();assert(!s.overflow);assert.deepEqual(errors,[]);results.push({viewport:label,case:name,...s});writeFileSync(`${out}/production.json`,JSON.stringify(results,null,2));await p.screenshot({path:`${out}/production-${label}-${name}.png`,fullPage:true});console.log(label,name,s.polygons.length);return s;}
 async function click(sel){await p.$eval(sel,e=>e.scrollIntoView({block:'center'}));await p.click(sel);await delay(900);}
 async function nil(name){await p.mouse.move(0,0);await p.$eval('.leaflet-container',e=>e.scrollIntoView({block:'center'}));await p.evaluate(name=>{const m=window.__qaMap();let t;m.eachLayer(l=>{if(l.options?.vpZoneName===name&&l.getBounds)t=l;});if(!t)throw Error('Missing polygon '+name);m.fitBounds(t.getBounds(),{padding:[60,60],maxZoom:14,animate:false});},name);await delay(900);const pt=await p.evaluate(name=>{const m=window.__qaMap();let t;m.eachLayer(l=>{if(l.options?.vpZoneName===name&&l.getBounds)t=l;});const r=m.getContainer().getBoundingClientRect(),size=m.getSize();for(let y=70;y<size.y-65;y+=7)for(let x=65;x<size.x-65;x+=7)if([[x,y],[x-4,y],[x+4,y],[x,y-4],[x,y+4]].every(pt=>t._containsPoint(m.latLngToLayerPoint(m.containerPointToLatLng(pt)))))return {x:r.left+x,y:r.top+y};throw Error('No interior point');},name);await p.evaluate(name=>{const m=window.__qaMap();m.eachLayer(l=>{if(l.options?.vpZoneName===name&&l.getBounds){window.__qaClicks??=[];l.on('click',()=>window.__qaClicks.push({name,at:Date.now()}));}});},name);await p.mouse.move(pt.x,pt.y);await delay(250);const hover=await state();assert(hover.polygons.find(l=>l.name===name)?.weight>2,'actual hover highlight');const hit=await p.evaluate(pt=>({tag:document.elementFromPoint(pt.x,pt.y)?.tagName,cls:document.elementFromPoint(pt.x,pt.y)?.className,zoom:window.__qaMap()?.getZoom()}),pt);await p.mouse.click(pt.x,pt.y);await delay(1200);console.log('nil click',name,JSON.stringify({point:pt,hit,clicks:await p.evaluate(()=>window.__qaClicks)}));}
 try{
 await p.waitForSelector('#step2-search-input',{timeout:60000});await p.type('#step2-search-input','Via Antonio Oroboni, Milano',{delay:25});await p.waitForFunction(()=>[...document.querySelectorAll('div[style]')].some(e=>/Oroboni/.test(e.innerText)&&/indirizzo\/punto/.test(e.innerText)&&e.innerText.length<180),{timeout:60000});await p.evaluate(()=>[...document.querySelectorAll('div[style]')].filter(e=>/Oroboni/.test(e.innerText)&&/indirizzo\/punto/.test(e.innerText)&&e.innerText.length<180).at(-1).click());
 await p.waitForFunction(()=>{let n=0;window.__qaMap()?.eachLayer(l=>{if(l.options?.vpZoneType==='nil')n++;});return n===88;},{timeout:90000});
 let s=await snap('initial');assert(s.boundary>0);assert(s.polygons.find(l=>l.name==='BRUZZANO').fill<.2);assert(s.summary.includes('Da scegliere'));assert(s.points.length>0);
 await click('[data-testid=map-toggle-nil]');assert.equal((await state()).polygons.length,0);await click('[data-testid=map-toggle-nil]');await click('.vp-milano-mode-card.is-nil');await nil('BRUZZANO');s=await snap('nil-add');assert(s.polygons.find(l=>l.name==='BRUZZANO').fill>=.3);assert(s.summary.includes('7.524'));await p.type('#vp-milano-nil-search','BRUZZANO');await p.waitForSelector('[data-nil-toggle=remove]');
 await nil('BRUZZANO');await p.waitForFunction(()=>{const m=window.__qaMap();let fill;m?.eachLayer(l=>{if(l.options?.vpZoneName==='BRUZZANO')fill=l.options.fillOpacity;});return fill<.2;},{timeout:10000});s=await snap('nil-remove');assert(s.polygons.find(l=>l.name==='BRUZZANO').fill<.2);assert(s.summary.includes('Da scegliere'));
 await nil('BRUZZANO');await nil('COMASINA');s=await snap('nil-multi');assert(s.summary.includes('BRUZZANO, COMASINA'));assert(s.polygons.filter(l=>l.fill>=.3).length===2);
 await click('.vp-milano-mode-card.is-radius');for(const [i,km] of [.5,1,2,3].entries()){await p.waitForSelector('.vp-milano-radius-presets button:not([disabled])',{timeout:90000});await p.$$eval('.vp-milano-radius-presets button',(es,i)=>es[i].click(),i);await p.waitForSelector('.vp-milano-radius-presets button:not([disabled])',{timeout:90000});await delay(2000);s=await snap(`radius-${km}`);assert(s.points.some(l=>l.radius===km*1000));assert(s.polygons.some(l=>l.type==='nil'));}
 assert(s.polygons.some(l=>l.type==='municipality'));assert(s.rows.length>1);assert(s.summary.includes('Quota delle famiglie stimate nel raggio'));await click('[data-testid=map-toggle-comuni]');assert(!(await state()).polygons.some(l=>l.type==='municipality'));await click('[data-testid=map-toggle-comuni]');await click('[data-testid=map-toggle-nil]');assert(!(await state()).polygons.some(l=>l.type==='nil'));await click('[data-testid=map-toggle-nil]');
 await click('.vp-milano-mode-card.is-nil');await p.waitForFunction(()=>{let n=0;window.__qaMap()?.eachLayer(l=>{if(l.options?.vpZoneType==='nil')n++;});return n===88;},{timeout:90000});await delay(2500);await nil('BRUZZANO');s=await snap('return-nil');assert(s.polygons.find(l=>l.name==='BRUZZANO').fill>=.3);console.log('PASS production',label);
 }catch(e){await p.screenshot({path:`${out}/production-${label}-failure.png`,fullPage:true});writeFileSync(`${out}/production-${label}-failure.json`,JSON.stringify({error:e.stack,state:await state(),network},null,2));throw e;}finally{writeFileSync(`${out}/production-${label}-network.json`,JSON.stringify(network,null,2));await ctx.close();}
}}finally{await browser.close();}
