// Studio Mappa — generazione automatica sulla RETE STRADALE REALE.
// Etichetta OBBLIGATA: "N% della rete stradale selezionata" (mai "copertura
// finale"). Il risultato e' editabile con gli strumenti manuali.
import { useState } from 'react';
import { btn, chip, input, panel, panelTitle } from './mapStudioStyles.js';
import { AUTO_PRESETS, AUTO_MIN, AUTO_MAX, clampAutoPercent, loadRoadNetwork, buildAutoResult } from './mapStudioAuto.js';
import { assignAllToOperator } from './mapStudioOperatorSplit.js';
import { boundaryCentroid, formatDistance } from './mapStudioGeometry.js';

export function AutoCoveragePanel({ project, ops, drawing, roadNet, setRoadNet, onAutoGenerated }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const auto = project.auto;
  const percent = clampAutoPercent(auto.percent);
  // operatore assegnato all'automatico = quello scelto nel select, altrimenti
  // l'operatore attivo in disegno (coerenza col tab Operatori).
  const chosenOperatorId = auto.operatorId || drawing.activeOperatorId || project.operators[0]?.id || null;

  const originLatLng = auto.originMode === 'click' && auto.originPoint
    ? auto.originPoint
    : (project.center || boundaryCentroid(project.boundary));

  async function ensureNetwork() {
    if (roadNet) return roadNet;
    const net = await loadRoadNetwork(project.municipality, project.boundary);
    setRoadNet(net);
    return net;
  }

  async function handleGenerate() {
    setError(null);
    if (!project.boundary || !project.municipality) { setError('Serve un comune con confine reale.'); return; }
    if (!originLatLng) { setError('Origine non determinata.'); return; }
    setBusy(true);
    try {
      const net = await ensureNetwork();
      if (!net) { setError('Rete stradale reale non disponibile per questo comune.'); setBusy(false); return; }
      const result = buildAutoResult(net, originLatLng, percent);
      if (!result.ok) { setError('Selezione automatica non riuscita.'); setBusy(false); return; }
      const opId = chosenOperatorId;
      const opColor = project.operators.find((o) => o.id === opId)?.color || null;
      // FASE 1: tutte le linee generate all'operatore scelto (nessun bilanciamento).
      const assigned = assignAllToOperator(result.lines, opId);
      // REGENERA = sostituisce SOLO l'automatico DI QUESTO operatore (gli altri
      // operatori mantengono la loro copertura automatica). Nessun duplicato.
      ops.clearFeatures((f) => f.source === 'auto' && f.operatorId === opId);
      ops.addFeatures(
        assigned.map((a) => ({
          operatorId: a.operatorId,
          type: 'line',
          source: 'auto',
          style: opColor ? { color: opColor } : null, // colore operatore stampato sul feature
          geometry: a.geometry,
        })),
        'auto',
        `Automatico ${percent}% → ${project.operators.find((o) => o.id === opId)?.name || 'operatore'}`,
      );
      if (typeof onAutoGenerated === 'function') onAutoGenerated();
      ops.setAuto({ lastResult: {
        requestedPercent: result.requestedPercent,
        networkSelectedPercent: result.networkSelectedPercent,
        totalNetworkM: result.totalNetworkM,
        selectedNetworkM: result.selectedNetworkM,
        waysSelected: result.waysSelected,
        waysTotal: result.waysTotal,
        label: result.networkPercentLabel,
        at: new Date().toISOString(),
      } });
    } catch (e) {
      setError(e?.message || 'Errore generazione automatica.');
    } finally {
      setBusy(false);
    }
  }

  const last = auto.lastResult;

  return (
    <div style={panel}>
      <p style={panelTitle}>Automatico — rete stradale reale</p>

      <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap', alignItems: 'center' }}>
        {AUTO_PRESETS.map((p) => (
          <button key={p} type="button" onClick={() => ops.setAuto({ percent: p })} style={chip(percent === p)}>{p}%</button>
        ))}
      </div>
      <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginTop: 6 }}>
        <input
          type="range"
          min={AUTO_MIN}
          max={AUTO_MAX}
          step="1"
          value={percent}
          onChange={(e) => ops.setAuto({ percent: Number(e.target.value) })}
          style={{ flex: 1 }}
        />
        <b style={{ minWidth: 42, textAlign: 'right' }}>{percent}%</b>
      </div>

      <div style={{ marginTop: 8, display: 'flex', gap: 6, alignItems: 'center', flexWrap: 'wrap' }}>
        <span style={{ fontSize: 11.5, color: 'rgba(255,255,255,.7)' }}>Origine</span>
        <button type="button" onClick={() => ops.setAuto({ originMode: 'center' })} style={chip(auto.originMode === 'center')}>centro comune</button>
        <button type="button" onClick={() => ops.setAuto({ originMode: 'click', originPoint: drawing.hoverPoint || project.center })} style={chip(auto.originMode === 'click')}>clic su mappa</button>
      </div>

      <div style={{ marginTop: 8 }}>
        <span style={{ fontSize: 11.5, color: 'rgba(255,255,255,.7)' }}>Operatore assegnato</span>
        <select
          style={{ ...input, marginTop: 4 }}
          value={chosenOperatorId || ''}
          onChange={(e) => ops.setAuto({ operatorId: e.target.value })}
        >
          {project.operators.map((op) => <option key={op.id} value={op.id}>{op.name}</option>)}
        </select>
        {chosenOperatorId && (
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, marginTop: 4, fontSize: 11 }}>
            <span style={{ width: 12, height: 12, borderRadius: 3, background: project.operators.find((o) => o.id === chosenOperatorId)?.color, border: '1px solid rgba(255,255,255,.3)' }} />
            le linee generate useranno questo colore
          </span>
        )}
      </div>

      <button type="button" onClick={handleGenerate} disabled={busy} style={{ ...btn(true), marginTop: 10, width: '100%' }}>
        {busy ? 'Generazione…' : `Genera ${percent}% della rete`}
      </button>
      {error && <p style={{ color: '#fca5a5', fontSize: 11, marginTop: 6 }}>{error}</p>}

      {last && (
        <div style={{ marginTop: 10, borderTop: '1px solid rgba(255,255,255,.1)', paddingTop: 8, fontSize: 11.5 }}>
          <p style={{ margin: 0, fontWeight: 900, color: '#93c5fd' }}>{last.label}</p>
          <p style={{ margin: '4px 0 0', color: 'rgba(255,255,255,.7)' }}>
            Rete selezionata: {formatDistance(last.selectedNetworkM)} su {formatDistance(last.totalNetworkM)}
            {' '}({last.networkSelectedPercent}% · {last.waysSelected}/{last.waysTotal} vie)
          </p>
          <p style={{ margin: '4px 0 0', color: 'rgba(255,255,255,.45)' }}>
            NB: e' la % di RETE selezionata, non la copertura d'area. Le due metriche sono nei KPI, separate.
          </p>
        </div>
      )}
    </div>
  );
}
