// Studio Mappa — pagina Admin autonoma. NON dipende da una campagna, NON e'
// montata dentro GpsMonitor, NON scrive dati reali. Route /admin/map-studio
// protetta da AdminGuard (in AppRouter).

import { useEffect, useMemo, useState } from 'react';
import { AdminLayout } from '../AdminLayout.jsx';
import { MapStudioCanvas } from './MapStudioCanvas.jsx';
import { MapStudioToolbar } from './MapStudioToolbar.jsx';
import { MapStudioProjectPanel } from './ProjectPanel.jsx';
import { OperatorsPanel } from './OperatorsPanel.jsx';
import { OperatorStylePanel } from './OperatorStylePanel.jsx';
import { LayersPanel } from './LayersPanel.jsx';
import { ManualToolsPanel } from './ManualToolsPanel.jsx';
import { AutoCoveragePanel } from './AutoCoveragePanel.jsx';
import { KpiPanel } from './KpiPanel.jsx';
import { SimulationPanel } from './SimulationPanel.jsx';
import { useMapStudioProject } from './useMapStudioProject.js';
import { useMapStudioDrawing } from './useMapStudioDrawing.js';
import { loadProject, getLastProjectId } from './mapStudioStorage.js';
import { createProject, createOperator } from './mapStudioProject.js';

function initialProject() {
  const lastId = getLastProjectId();
  const restored = lastId ? loadProject(lastId) : null;
  if (restored) return restored;
  return createProject({
    name: 'Progetto senza titolo',
    operators: [createOperator({ index: 0, name: 'Operatore 1' }), createOperator({ index: 1, name: 'Operatore 2' })],
  });
}

const TABS = [
  { id: 'project', label: 'Progetto' },
  { id: 'operators', label: 'Operatori' },
  { id: 'design', label: 'Design' },
  { id: 'manual', label: 'Manuale' },
  { id: 'auto', label: 'Automatico' },
  { id: 'layers', label: 'Layer' },
  { id: 'kpi', label: 'KPI' },
  { id: 'sim', label: 'Simula' },
];

export function MapStudioPage({ onNav }) {
  const [seed] = useState(initialProject);
  const store = useMapStudioProject(seed);
  const { project, dirty, notice } = store;

  const [roadNet, setRoadNet] = useState(null);
  const [soloOperatorId, setSoloOperatorId] = useState(null);
  const [tab, setTab] = useState('project');
  // incrementato dopo ogni "Genera": la mappa fa fitBounds sulla copertura
  // automatica appena creata così è subito visibile.
  const [fitAutoTick, setFitAutoTick] = useState(0);

  const roadWays = useMemo(() => (roadNet?.ways || []).map((w) => w.geometry), [roadNet]);
  // la rete cambia col comune: azzera quando cambia progetto/comune
  useEffect(() => { setRoadNet(null); }, [project.id, project.municipality]);

  const drawing = useMapStudioDrawing({ project, ops: store.ops, roadWays });

  // filtro "solo operatore": operatorsById con visibilita' forzata
  const viewOperatorsById = useMemo(() => {
    const m = new Map();
    for (const op of project.operators) {
      m.set(op.id, soloOperatorId ? { ...op, visible: op.id === soloOperatorId } : op);
    }
    return m;
  }, [project.operators, soloOperatorId]);

  // scorciatoie undo/redo
  useEffect(() => {
    const onKey = (e) => {
      const mod = e.ctrlKey || e.metaKey;
      if (!mod) return;
      if (e.key.toLowerCase() === 'z' && !e.shiftKey) { e.preventDefault(); store.history.undo(); }
      else if ((e.key.toLowerCase() === 'z' && e.shiftKey) || e.key.toLowerCase() === 'y') { e.preventDefault(); store.history.redo(); }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [store.history]);

  const breadcrumbs = [
    { label: 'Dashboard', href: '/admin' },
    { label: 'Studio Mappa' },
  ];

  // Mapping tab → pannello: ESATTAMENTE uno per volta. Nessun pannello
  // "sempre montato" sopra gli altri (la toolbar strumenti vive solo nel tab
  // Manuale). Vietato che due pannelli coesistano nella colonna sinistra.
  function renderActivePanel() {
    switch (tab) {
      case 'project':
        return <MapStudioProjectPanel project={project} dirty={dirty} persistence={store.persistence} ops={store.ops} />;
      case 'operators':
        return (
          <OperatorsPanel
            project={project}
            ops={store.ops}
            drawing={drawing}
            soloOperatorId={soloOperatorId}
            setSoloOperatorId={setSoloOperatorId}
          />
        );
      case 'design':
        return <OperatorStylePanel project={project} ops={store.ops} drawing={drawing} />;
      case 'manual':
        return <ManualToolsPanel project={project} ops={store.ops} drawing={drawing} />;
      case 'auto':
        return (
          <AutoCoveragePanel
            project={project}
            ops={store.ops}
            drawing={drawing}
            roadNet={roadNet}
            setRoadNet={setRoadNet}
            onAutoGenerated={() => setFitAutoTick((t) => t + 1)}
          />
        );
      case 'layers':
        return <LayersPanel project={project} ops={store.ops} />;
      case 'kpi':
        return <KpiPanel project={project} />;
      case 'sim':
        return <SimulationPanel project={project} />;
      default:
        return null;
    }
  }

  return (
    <AdminLayout
      title="Studio Mappa"
      subtitle="Strumento autonomo di progettazione copertura — indipendente da campagne, Monitor e Driver."
      breadcrumbs={breadcrumbs}
      onNav={onNav}
    >
      <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap', marginBottom: 10 }}>
        <span style={{ fontSize: 13, fontWeight: 900 }}>Progetto: {project.name}</span>
        <span style={{ fontSize: 12, color: 'rgba(255,255,255,.55)' }}>
          {project.municipality ? `${project.municipality}${project.province ? ` (${project.province})` : ''}` : 'nessun comune'}
          {' · '}{project.features.length} elementi · {project.operators.length} operatori
          {dirty ? ' · • non salvato' : ` · ${project.status}`}
        </span>
        {notice && (
          <span style={{ fontSize: 12, fontWeight: 800, color: notice.type === 'error' ? '#fca5a5' : '#86efac' }}>{notice.text}</span>
        )}
      </div>

      {!project.municipality && (
        <div style={{
          marginBottom: 10, padding: '8px 12px', borderRadius: 8, fontSize: 12.5, fontWeight: 700,
          background: 'rgba(37,99,235,.14)', border: '1px solid rgba(37,99,235,.4)', color: '#bfdbfe',
        }}>
          Seleziona un comune nel tab <b>Progetto</b> per iniziare — la mappa mostrerà solo quell’area.
        </div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: 'minmax(320px, 380px) 1fr', gap: 12, alignItems: 'start' }}>
        {/* colonna sinistra: pannelli a tab */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10, maxHeight: '78vh', overflowY: 'auto', paddingRight: 4 }}>
          <div style={{ display: 'flex', gap: 4, flexWrap: 'wrap' }}>
            {TABS.map((t) => (
              <button
                key={t.id}
                type="button"
                onClick={() => setTab(t.id)}
                style={{
                  border: '1px solid',
                  borderColor: tab === t.id ? '#2563eb' : 'rgba(255,255,255,.16)',
                  background: tab === t.id ? '#2563eb' : 'rgba(255,255,255,.05)',
                  color: '#fff', borderRadius: 7, padding: '6px 10px', fontSize: 11.5, fontWeight: 800, cursor: 'pointer',
                }}
              >
                {t.label}
              </button>
            ))}
          </div>

          {/* La toolbar strumenti (Seleziona / Matita / Poligono / Gomma /
              Split / Join / Sposta vertice) appartiene SOLO al tab Manuale —
              non è più un pannello sempre montato sopra gli altri. */}
          {tab === 'manual' && <MapStudioToolbar drawing={drawing} history={store.history} />}

          {renderActivePanel()}
        </div>

        {/* colonna destra: mappa */}
        <div style={{ height: '78vh', minHeight: 480 }}>
          <MapStudioCanvas
            project={project}
            operatorsById={viewOperatorsById}
            roadWays={roadWays}
            drawing={drawing}
            fitAutoTick={fitAutoTick}
          />
        </div>
      </div>

      {/* barra stato / timeline / undo-redo */}
      <div style={{
        marginTop: 10, display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap',
        borderTop: '1px solid rgba(255,255,255,.1)', paddingTop: 8, fontSize: 12, color: 'rgba(255,255,255,.7)',
      }}>
        <span>Strumento: <b style={{ color: '#fff' }}>{drawing.tool}</b></span>
        <span>Snap: <b style={{ color: '#fff' }}>{drawing.snapMode}</b></span>
        <span>Storia: {store.history.undoDepth} indietro / {store.history.redoDepth} avanti</span>
        <button type="button" onClick={store.history.undo} disabled={!store.history.canUndo} style={{ ...miniBtn, opacity: store.history.canUndo ? 1 : 0.4 }}>Undo</button>
        <button type="button" onClick={store.history.redo} disabled={!store.history.canRedo} style={{ ...miniBtn, opacity: store.history.canRedo ? 1 : 0.4 }}>Redo</button>
        <span style={{ marginLeft: 'auto', color: 'rgba(255,255,255,.4)' }}>
          {store.history.timeline.slice(-6).map((e) => e.kind).join(' → ') || 'nessuna modifica'}
        </span>
      </div>
    </AdminLayout>
  );
}

const miniBtn = {
  border: '1px solid rgba(255,255,255,.16)', background: 'rgba(255,255,255,.05)', color: '#fff',
  borderRadius: 6, padding: '3px 10px', fontSize: 11, fontWeight: 800, cursor: 'pointer',
};

export default MapStudioPage;
