import React from 'react';
import { FIELDS, SOURCE_LABELS } from './feasibilitySchemas.js';
import { buildInfoMailtoUrl, buildInfoWhatsAppUrl, HAS_SUPPORT_WHATSAPP } from '../../../lib/contactConfig.js';
export const money = value => value == null ? 'Non definito' : new Intl.NumberFormat('it-IT', { style: 'currency', currency: 'EUR' }).format(value);
export const number = value => value == null ? 'Non raggiungibile' : new Intl.NumberFormat('it-IT', { maximumFractionDigits: 4 }).format(value);
export const percent = value => value == null ? 'Non definito' : `${number(value * 100)}%`;
export const DISCLAIMER = "L'analisi è una simulazione economica basata sui dati forniti e sulle ipotesi indicate. Non garantisce risultati commerciali o finanziari.";
export default function FeasibilityReport({ inputs, result, narrative, aiState, unusualMargin, onEdit, onRetry, snapshot }) {
  const realistic = result.scenarios[1];
  const note = key => narrative?.[key] || 'Interpretazione AI temporaneamente non disponibile.';
  const cards = [['Costo campagna', money(result.campaignCost), 'cost'], ['Clienti per pareggio', number(result.breakEvenCustomers), 'break-even'], ['Conversione per pareggio', percent(result.breakEvenConversion), 'break-even-conversion'], ['ROI scenario realistico', realistic.roi == null ? 'Non definito (costo zero)' : `${number(realistic.roi)}%`, 'roi'], ['Clienti attesi — realistico', number(realistic.expectedCustomers), 'customers'], ['Valutazione', result.classification, 'classification']];
  return <article className="vf-report" aria-labelledby="vf-report-title">
    {snapshot && <section className="vf-panel"><h2>Studio di Fattibilità · VolantiniPro</h2><p>Report {snapshot.id}</p><p>{new Date(snapshot.created_at).toLocaleString("it-IT")}</p><p>Motore {snapshot.engine_version} · Prompt {snapshot.prompt_version} · Report {snapshot.report_version} · Prezzi {snapshot.pricing_version}</p><p className="vf-small">SHA256: {snapshot.snapshot_sha256}</p><p>Versione acquistata immutabile. Nuovi dati richiedono una nuova analisi.</p></section>}<header className="vf-report-heading"><span className="vf-eyebrow">VolantiniPro · Studio di Fattibilità AI</span><h1 id="vf-report-title">Studio di Fattibilità AI — Campagna Pubblicitaria</h1><p className="vf-report-subtitle">Analisi economica, break-even e scenari</p><p>{DISCLAIMER}</p><div className="vf-actions vf-no-print">{onEdit && <button onClick={onEdit} disabled={aiState === 'loading'}>Modifica dati e ipotesi</button>}<button onClick={() => window.print()}>Stampa / Salva PDF</button></div></header>
    <div className="vf-kpis">{cards.map(([label, value, id]) => <section className="vf-kpi" key={id}><h3>{label}</h3><strong data-testid={`kpi-${id}`}>{value}</strong></section>)}</div>
    <p role="status" className="vf-ai-status">{aiState === 'loading' ? 'Calcoli pronti. Preparazione dell’interpretazione AI…' : aiState === 'ready' ? 'Interpretazione AI disponibile. Numeri e valutazione provengono esclusivamente dal motore di calcolo.' : 'Interpretazione AI temporaneamente non disponibile.'}</p>
    {aiState === 'failed' && onRetry && <button className="vf-no-print" onClick={onRetry}>Riprova interpretazione AI</button>}
    <section className="vf-panel"><h3>1. Sintesi esecutiva</h3><p>{note('executive')}</p><p>Esito della simulazione: <strong>{result.classification}</strong>.</p></section>
    <div className="vf-report-pair"><section className="vf-panel"><h3>2. Attività</h3><p>{inputs.businessType.value} · {inputs.city.value}</p>{inputs.businessDescription.value && <p>{inputs.businessDescription.value}</p>}<p>{note('business')}</p></section><section className="vf-panel"><h3>3. Campagna</h3><p>{inputs.serviceType.value || 'Servizio non indicato'} · {inputs.campaignArea.value || inputs.city.value}</p><p>{number(inputs.flyerQuantity.value)} volantini · {money(result.campaignCost)}</p></section></div>
    <section className="vf-panel"><h3>4. Indicatori finanziari</h3><p>Ricavo medio cliente: {money(inputs.averageCustomerRevenue.value)}. Margine medio: {money(inputs.averageCustomerMargin.value)}.</p><p>Conversione necessaria per l’obiettivo di {number(inputs.targetNewCustomers.value)} clienti: <strong data-testid="target-conversion">{percent(result.targetConversion)}</strong>.</p>{result.targetConversion > 1 && <p>L’obiettivo supera i volantini disponibili: non è raggiungibile con l’ipotesi di un nuovo cliente per volantino.</p>}</section>
    <section className="vf-panel"><h3>5. Analisi del pareggio</h3><p>{result.breakEvenCustomers === null ? 'Con margine nullo e costo positivo il pareggio non è raggiungibile.' : `Servono ${number(result.breakEvenCustomers)} clienti interi per recuperare il costo; conversione richiesta: ${percent(result.breakEvenConversion)}.`}</p>{result.breakEvenConversion > 1 && <p>Il pareggio richiede più clienti dei volantini disponibili.</p>}<p className="vf-small">Clienti per pareggio = arrotondamento per eccesso di costo ÷ margine. Conversione = clienti per pareggio ÷ volantini.</p></section>
    <section className="vf-panel"><h3>6. Analisi degli scenari</h3><p>Clienti attesi sono valori medi ipotetici. L’intervallo intero è un’interpretazione pratica, non un intervallo di confidenza.</p><div className="vf-table-wrap" tabIndex={0} role="region" aria-label="Tabella scenari scorrevole"><table><caption>Scenari deterministici: ipotesi modificabili</caption><thead><tr>{['Scenario', 'Conversione', 'Clienti attesi', 'Ricavi', 'Contributo', 'Costo', 'CAC', 'Risultato netto', 'ROI', 'Pareggio'].map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{result.scenarios.map(s => <tr key={s.name}><th scope="row">{s.name}</th><td>{percent(s.conversionRate)}</td><td>{number(s.expectedCustomers)}<small>circa {number(s.practicalRange[0])}–{number(s.practicalRange[1])}</small></td><td>{money(s.revenueGenerated)}</td><td>{money(s.contribution)}</td><td>{money(s.campaignCost)}</td><td>{money(s.cac)}</td><td>{money(s.netResult)}</td><td>{s.roi == null ? 'Non definito' : `${number(s.roi)}%`}</td><td>{s.breakEvenAchieved ? 'SÌ' : 'NO'}</td></tr>)}</tbody></table></div></section>
    <section className="vf-panel"><h3>7. ROI e risultato all’obiettivo</h3><dl className="vf-metrics">{[['Contributo', money(result.target.contribution), 'target-contribution'], ['Risultato netto', money(result.target.netResult), 'target-net'], ['ROI', result.target.roi == null ? 'Non definito' : `${number(result.target.roi)}%`, 'target-roi'], ['CAC', money(result.target.cac), 'target-cac']].map(([label, value, id]) => <div key={id}><dt>{label}</dt><dd data-testid={id}>{value}</dd></div>)}</dl><p>{note('interpretation')}</p><p className="vf-small">Contributo = clienti × margine; risultato netto = contributo − costo; ROI = risultato netto ÷ costo × 100. Con costo zero il ROI non è definito. Ricavi = clienti × ricavo medio.</p></section>
    <section className="vf-panel"><h3>8. Economia di acquisizione cliente</h3><p>Tetto CAC sul margine del primo acquisto: <strong>{money(result.firstPurchaseCACCeiling)}</strong>. CAC = costo ÷ nuovi clienti; senza clienti non è definito.</p>{result.ltvRevenueCeiling != null && <p>Limite teorico sui ricavi LTV: {money(result.ltvRevenueCeiling)}. Non è un tetto di profitto sostenibile: mancano costi futuri, durata e rischio di riacquisto.</p>}</section>
    <section className="vf-panel"><h3>9. Considerazioni sul mercato e sulla campagna</h3><p>{note('market')}</p><p>Non sono stati usati benchmark esterni o stime automatiche della domanda locale.</p></section>
    <section className="vf-panel"><h3>10. SWOT</h3><dl className="vf-swot">{[['Punti di forza', 'strength'], ['Debolezze', 'weakness'], ['Opportunità', 'opportunity'], ['Minacce', 'threat']].map(([label, key]) => <div key={key}><dt>{label}</dt><dd>{note(key)}</dd></div>)}</dl></section>
    <section className="vf-panel"><h3>11. Rischi</h3><p>{note('risks')}</p><p>Le conversioni non sono probabilità validate. Il modello non comprende costi fissi, imposte o ricavi futuri nei risultati della campagna.</p></section>
    <section className="vf-panel"><h3>12. Azioni consigliate</h3><p>{note('actions')}</p></section>
    <section className="vf-panel"><h3>13. Ipotesi e fonti dei dati</h3><p>Queste sono stime, non garanzie.</p>{unusualMargin && <p>È stato confermato esplicitamente un margine superiore al ricavo.</p>}<dl className="vf-sources">{Object.keys(FIELDS).map(key => <div key={key}><dt>{FIELDS[key].label}</dt><dd>{inputs[key].value == null ? 'Non disponibile' : FIELDS[key].rate ? percent(inputs[key].value) : String(inputs[key].value)}<small>{SOURCE_LABELS[inputs[key].source]}</small></dd></div>)}</dl><p className="vf-small">Conversioni iniziali: 0,03% / 0,05% / 0,10%. Applicazione facoltativa dello storico: × 0,6 / × 1 / × 2, massimo 100%. I valori effettivamente usati sono quelli riportati sopra. LTV e altri dati facoltativi non modificano il risultato del primo acquisto.</p></section>
    <section className="vf-panel"><h3>14. Valutazione finale</h3><strong>{result.classification}</strong><p>{result.classificationRules}</p><p>{note('final')}</p><p>{DISCLAIMER}</p><small>Motore {result.engineVersion} · Valutazione della simulazione, non consulenza di investimento.</small>
      <div className="vf-actions vf-no-print">
        <a className="vf-button" href="/analisi-campagna">Calcola / aggiorna preventivo</a>
        <a className="vf-button vf-primary" href="/configuratore">Avvia campagna</a>
        <a className="vf-button" href={buildInfoMailtoUrl()}>Parla con un consulente</a>
        {HAS_SUPPORT_WHATSAPP && <a className="vf-button" href={buildInfoWhatsAppUrl()} target="_blank" rel="noopener noreferrer">Scrivi su WhatsApp</a>}
        <button type="button" onClick={() => window.print()}>Scarica PDF</button>
      </div>
    </section>
    <div className="vf-print-footer"><span>VolantiniPro · Studio di Fattibilità AI — Campagna Pubblicitaria</span><span>{inputs.businessType?.value || 'Attività'} · {inputs.city?.value || 'Zona'}</span></div>
  </article>;
}
