import React, { useEffect, useState } from 'react';
import { commerce, errorText } from './feasibilityCommerce.js';
import FeasibilityAuth from './FeasibilityAuth.jsx';
import FeasibilityReport, { money } from './FeasibilityReport.jsx';
import { SUPPORT_EMAIL, SUPPORT_WHATSAPP, HAS_SUPPORT_WHATSAPP } from '../../../lib/contactConfig.js';
import './feasibility.css';

function PaymentContact({ purchase }) {
 const text=`Buongiorno, vorrei le istruzioni per pagare lo Studio di Fattibilità. Acquisto ${purchase.id}, importo ${money(purchase.amount_cents/100)}.`;
 return <div className="vf-actions">{HAS_SUPPORT_WHATSAPP&&<a target="_blank" rel="noopener noreferrer" href={`https://wa.me/${SUPPORT_WHATSAPP}?text=${encodeURIComponent(text)}`}>Richiedi istruzioni WhatsApp</a>}<a href={`mailto:${SUPPORT_EMAIL}?subject=${encodeURIComponent('Pagamento Studio di Fattibilità')}&body=${encodeURIComponent(text)}`}>Richiedi istruzioni email</a><p>Richiedere istruzioni o aggiornare la pagina non conferma il pagamento.</p></div>;
}
function AdminVerification({ refresh }) {
 const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState('verify_eligibility');
 async function submit(e) {
   e.preventDefault();setBusy(true);setNotice('');const f=new FormData(e.currentTarget);
   const payload={campaignId:f.get('campaign'),ownerId:f.get('owner'),grossCents:Math.round(Number(f.get('amount'))*100),amountCents:Math.round(Number(f.get('amount'))*100),confirmedAt:f.get('date')?new Date(String(f.get('date'))).toISOString():undefined,reference:f.get('reference'),verified:f.get('verified')==='on'};
   try {await commerce(mode,payload);setNotice('Verifica registrata.');await refresh();}catch(e){setNotice(errorText(e));}finally{setBusy(false);}
 }
 return <section className="vf-panel"><h2>Verifica campagna con credito</h2><p>Verifica importo, titolare, conferma e saldo sui documenti commerciali. I dati della campagna inseriti dal cliente non costituiscono prova.</p><label>Operazione<select value={mode} onChange={e=>setMode(e.target.value)}><option value="verify_eligibility">Verifica idoneità della campagna</option><option value="verify_residual">Verifica incasso del residuo</option></select></label><form onSubmit={submit}><label>ID campagna<input name="campaign" required /></label>{mode==='verify_eligibility'&&<><label>ID cliente verificato<input name="owner" required /></label><label>Data e ora della conferma verificata<input name="date" type="datetime-local" step="1" required /></label></>}<label>{mode==='verify_eligibility'?'Importo lordo verificato (€)':'Residuo effettivamente ricevuto (€)'}<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Riferimento documentale<input name="reference" maxLength={200} required={mode==='verify_residual'} /></label><label className="vf-check"><input name="verified" type="checkbox" required />{mode==='verify_eligibility'?'Ho verificato titolare, importo, data, idoneità e che il lordo sia ancora interamente da versare.':'Ho verificato l’effettivo incasso del residuo indicato.'}</label><button disabled={busy}>Registra verifica Admin</button></form>{notice&&<p role="status">{notice}</p>}</section>;
}
function VerifyPurchase({ purchase, refresh }) {
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function submit(e){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await commerce('verify_payment',{purchaseId:purchase.id,reference:f.get('reference'),receiptVerified:f.get('verified')==='on'});await refresh();}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
 return <form onSubmit={submit}><label>Riferimento incasso verificato<input name="reference" minLength={3} maxLength={200} required /></label><label className="vf-check"><input name="verified" type="checkbox" required />{purchase.is_test?'Verifica sintetica TEST, nessun incasso reale':'Ho verificato l’effettivo incasso dello studio'}</label><button disabled={busy}>Conferma verifica incasso studio</button>{notice&&<p role="status">{notice}</p>}</form>;
}
export default function FeasibilityLibrary() {
 const [purchases,setPurchases]=useState([]),[campaigns,setCampaigns]=useState([]),[report,setReport]=useState(null),[auth,setAuth]=useState(false),[admin,setAdmin]=useState(false),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState({});
 async function load(){setBusy(true);setNotice('');try{let data;try{data=await commerce('library');setAdmin(false);const c=await commerce('campaigns');setCampaigns(c.campaigns);}catch(e){if(e.message!=='CLIENT_REQUIRED')throw e;data=await commerce('admin_list');setAdmin(true);}setPurchases(data.purchases);setAuth(false);}catch(e){if(e.message==='AUTH_REQUIRED')setAuth(true);else setNotice(errorText(e));}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 async function open(id){setBusy(true);try{const data=await commerce('report',{reportId:id});setReport(data.report);}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
 async function apply(creditId){setBusy(true);try{await commerce('apply_credit',{creditId,campaignId:selected[creditId]});await load();setNotice('Credito applicato. Il saldo verificato è disponibile nella pagina pagamento della campagna.');}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
 return <main className="vf-page"><div className="vf-shell"><header className="vf-heading vf-no-print"><h1>Le mie analisi</h1><a href="/analisi-campagna">Nuova analisi</a><div className="vf-actions"><button disabled={busy} onClick={load}>Aggiorna stato</button>{report&&<button onClick={()=>setReport(null)}>Torna alle analisi</button>}</div></header>{auth&&<FeasibilityAuth onSuccess={load}/>}<p role="status">{busy?'Caricamento…':notice}</p>{report?<FeasibilityReport snapshot={report} inputs={report.inputs_snapshot} result={report.outputs_snapshot} narrative={report.narrative_snapshot} unusualMargin={report.unusual_margin} aiState={report.narrative_snapshot?'ready':'failed'}/>:<>{admin&&<AdminVerification refresh={load}/>}<div>{purchases.map(p=>{const credit=p.credit,expired=credit&&Date.now()>=Date.parse(credit.expires_at);return <section key={p.id} className="vf-panel"><h2>{p.option==='study_campaign'?'Studio + Campagna':'Solo Studio di Fattibilità'}</h2><p>{p.preview?.city} {p.preview?.businessType} · {new Date(p.created_at).toLocaleDateString('it-IT')}</p><p>ID acquisto: {p.id}</p>{admin&&<p>ID cliente: {p.owner_id}</p>}{p.is_test&&<strong>TEST SINTETICO · nessun incasso reale</strong>}<p>{money(p.amount_cents/100)} · {p.status==='paid'?'Pagamento verificato':'In attesa di verifica pagamento'}</p>{p.status==='awaiting_payment'&&(admin?<VerifyPurchase purchase={p} refresh={load}/>:<PaymentContact purchase={p}/>)}{!admin&&p.status==='paid'&&p.report&&<button disabled={busy} onClick={()=>open(p.report.id)}>Apri report / PDF</button>}{credit&&<div><h3>Credito {money(credit.face_value_cents/100)}</h3><p>{credit.status==='applied'?'Credito utilizzato':expired?'Credito scaduto':'Credito disponibile'} · Valido fino al {new Date(credit.expires_at).toLocaleString('it-IT')}</p>{credit.status==='available'&&!expired&&<><p>Applica a una campagna dello stesso account, confermata nel periodo di validità e verificata da Admin. Il credito viene consumato una sola volta, senza residuo riutilizzabile.</p><label>Campagna<select value={selected[credit.id]||''} onChange={e=>setSelected({...selected,[credit.id]:e.target.value})}><option value="">Seleziona una campagna</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.title||c.id}</option>)}</select></label><button disabled={busy||!selected[credit.id]} onClick={()=>apply(credit.id)}>Applica credito</button></>}</div>}</section>;})}</div>{!auth&&!busy&&!purchases.length&&<p>Non ci sono acquisti disponibili per questo account.</p>}</>}</div></main>;
}
